name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ruff:
    runs-on: ubuntu-latest
    name: Lint with Ruff
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run Ruff linter
        run: uv run ruff check --output-format=github .

      - name: Run Ruff formatter
        run: uv run ruff format --check .

  pre-commit:
    runs-on: ubuntu-latest
    name: Pre-commit hooks
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install

      - name: Install pre-commit
        run: uv tool install pre-commit --with pre-commit-uv

      - name: Run pre-commit
        run: |
          # Run pre-commit and check if any files would be modified
          uv tool run pre-commit run --all-files --show-diff-on-failure || (
            echo "Pre-commit hooks would modify files. Please run 'pre-commit run --all-files' locally and commit the changes."
            exit 1
          )
